stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: node:lts-slim
  before_script:
    - npm install
  script:
    - npm run test

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t adriandotdev/emsp_v2 .
    - docker push adriandotdev/emsp_v2

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY sysnet@192.46.227.227 "
      sudo docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
      sudo docker ps -aq | xargs sudo docker stop | xargs sudo docker rm &&
      sudo docker run -d -p 4021:4021 adriandotdev/emsp_v2:latest"

