run_tests:
  image: node:lts-slim
  before_script:
    - npm install
  script:
    - npm run test

build_image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t emsp_v2 .
    - docker push emsp_v2
