stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: node:lts-slim
  before_script:
    - npm install
  script:
    - npm run test

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t adriandotdev/emsp_v2 .
    - docker push adriandotdev/emsp_v2

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY sysnet@192.46.227.227 "
      docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
      docker stop emsp_v2 || true &&
      docker rm emsp_v2 || true &&
      docker images | grep 'adriandotdev/emsp_v2' | awk '{print $3}' | xargs docker rmi -f || true &&
      docker pull adriandotdev/emsp_v2:latest &&
      docker run -d -p 4021:4021 --name emsp_v2 adriandotdev/emsp_v2:latest"
