variables:
  IMAGE_NAME: sysnet2024/emsp_v2
stages:
  # - test
  - build
  - deploy

# run_tests:
#   stage: test
#   image: node:lts-slim
#   before_script:
#     - npm install
#   script:
#     - npm run test

build_image:
  stage: build
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - unset DOCKER_HOST
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t sysnet2024/emsp_v2 .
    - docker push sysnet2024/emsp_v2

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $HOST "
      docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
      docker stop emsp_v2 || true &&
      docker rm emsp_v2 || true &&
      docker images | grep '$IMAGE_NAME' | awk '{print $3}' | xargs docker rmi -f || true &&
      docker pull $IMAGE_NAME &&
      docker run -d -p 4021:4021 --name emsp_v2 --mount type=bind,source=/data/logs,target=/var/www/emsp/logs --mount type=bind,source=/data/uploads,target=/var/www/emsp/public/images $IMAGE_NAME"
